// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVOvxRz5lEm4OrVYRixI1dtOpsIqG7tIQ',
    appId: '1:123328047417:web:1075a8d35958d261f960e8',
    messagingSenderId: '123328047417',
    projectId: 'master-focus-todo-ec624',
    authDomain: 'master-focus-todo-ec624.firebaseapp.com',
    storageBucket: 'master-focus-todo-ec624.appspot.com',
    measurementId: 'G-3YSP0S1JSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmG7l2XRUTwNCowYhn2OXcFygQDxoIqM',
    appId: '1:123328047417:android:87c1346b7a9f52f7f960e8',
    messagingSenderId: '123328047417',
    projectId: 'master-focus-todo-ec624',
    storageBucket: 'master-focus-todo-ec624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY9AEawpwxN3vFNfVYbUiDs3wvLzptRro',
    appId: '1:123328047417:ios:0260a79574568621f960e8',
    messagingSenderId: '123328047417',
    projectId: 'master-focus-todo-ec624',
    storageBucket: 'master-focus-todo-ec624.appspot.com',
    androidClientId: '123328047417-somjktsmph8irf1vk9h80rv5kapaotif.apps.googleusercontent.com',
    iosClientId: '123328047417-ptk3mmhjqv4875199204t98nhneuqk87.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterFocusTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY9AEawpwxN3vFNfVYbUiDs3wvLzptRro',
    appId: '1:123328047417:ios:0260a79574568621f960e8',
    messagingSenderId: '123328047417',
    projectId: 'master-focus-todo-ec624',
    storageBucket: 'master-focus-todo-ec624.appspot.com',
    androidClientId: '123328047417-somjktsmph8irf1vk9h80rv5kapaotif.apps.googleusercontent.com',
    iosClientId: '123328047417-ptk3mmhjqv4875199204t98nhneuqk87.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterFocusTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVOvxRz5lEm4OrVYRixI1dtOpsIqG7tIQ',
    appId: '1:123328047417:web:7770f81cc4931207f960e8',
    messagingSenderId: '123328047417',
    projectId: 'master-focus-todo-ec624',
    authDomain: 'master-focus-todo-ec624.firebaseapp.com',
    storageBucket: 'master-focus-todo-ec624.appspot.com',
    measurementId: 'G-VM76RMS00Z',
  );
}
